# Generated by Django 6.0.4 on 2026-04-07 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='pdf',
            field=models.FileField(default=1, upload_to='pdfs/'),
            preserve_default=False,
        ),
    ]
