# Generated by Django 6.0.4 on 2026-04-17 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_genero_anime_volume_capitulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='generos',
            field=models.ManyToManyField(null=True, related_name='animes', to='backend.genero'),
        ),
    ]
