# Generated by Django 6.0.4 on 2026-04-19 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_anime_total_capitulos_alter_capitulolido_lido'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
