# Generated by Django 6.0.4 on 2026-04-19 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_anime_atualizado_em'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='criado_em',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
