# Generated by Django 6.0.4 on 2026-04-19 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_anime_criado_em'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='atualizado_em',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
