# Generated by Django 6.0.4 on 2026-04-25 00:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Capitulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('numero', models.IntegerField()),
                ('visualizacoes', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Permissao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, unique=True)),
                ('descricao', models.TextField()),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='animes/')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('total_capitulos', models.PositiveIntegerField(default=0)),
                ('atualizado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_em', models.DateTimeField(auto_now=True)),
                ('generos', models.ManyToManyField(null=True, related_name='animes', to='backend.genero')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('grupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.grupo')),
            ],
        ),
        migrations.AddField(
            model_name='grupo',
            name='permissoes',
            field=models.ManyToManyField(blank=True, to='backend.permissao'),
        ),
        migrations.CreateModel(
            name='UsuarioCustom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('senha', models.CharField(max_length=255)),
                ('vip', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('grupos', models.ManyToManyField(blank=True, to='backend.grupo')),
            ],
        ),
        migrations.CreateModel(
            name='CapituloView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('capitulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='backend.capitulo')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.usuariocustom')),
            ],
        ),
        migrations.CreateModel(
            name='Volume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(unique=True)),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volumes', to='backend.anime')),
            ],
        ),
        migrations.AddField(
            model_name='capitulo',
            name='volume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capitulos', to='backend.volume'),
        ),
        migrations.CreateModel(
            name='Pagina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='capitulos_paginas/')),
                ('numero', models.PositiveIntegerField()),
                ('capitulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paginas', to='backend.capitulo')),
            ],
            options={
                'ordering': ['numero'],
                'unique_together': {('capitulo', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='CapituloLido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lido', models.BooleanField(default=False)),
                ('data_leitura', models.DateTimeField(auto_now=True)),
                ('capitulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.capitulo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.usuariocustom')),
            ],
            options={
                'unique_together': {('user', 'capitulo')},
            },
        ),
    ]
