# Generated by Django 6.0.4 on 2026-04-25 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='capitulo',
            unique_together={('volume', 'numero')},
        ),
    ]
