# Generated by Django 6.0.4 on 2026-04-17 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_anime_generos'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
