# Generated by Django 6.0.4 on 2026-04-19 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_anime_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapituloLido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lido', models.BooleanField(default=True)),
                ('data_leitura', models.DateTimeField(auto_now=True)),
                ('capitulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.capitulo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.usuariocustom')),
            ],
            options={
                'unique_together': {('user', 'capitulo')},
            },
        ),
    ]
