# Generated by Django 6.0.4 on 2026-04-19 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_capitulolido'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='total_capitulos',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='capitulolido',
            name='lido',
            field=models.BooleanField(default=False),
        ),
    ]
