# Generated by Django 6.0.4 on 2026-04-21 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_pagina'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagina',
            options={'ordering': ['numero']},
        ),
        migrations.RemoveField(
            model_name='capitulo',
            name='pdf',
        ),
        migrations.AlterField(
            model_name='pagina',
            name='numero',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='pagina',
            unique_together={('capitulo', 'numero')},
        ),
    ]
