# Generated by Django 6.0.4 on 2026-04-25 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_alter_capituloview_capitulo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permissao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='usuariocustom',
            name='entidade',
        ),
        migrations.AddField(
            model_name='usuariocustom',
            name='grupos',
            field=models.ManyToManyField(blank=True, to='backend.grupo'),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='nome',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='grupo',
            name='permissoes',
            field=models.ManyToManyField(blank=True, to='backend.permissao'),
        ),
    ]
