# Generated by Django 6.0.4 on 2026-04-07 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('genero', models.CharField(max_length=100)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='animes/')),
            ],
        ),
    ]
